project_id = "simgnodjhnpvyqqhwykg"

[functions.sync-stortinget]
verify_jwt = false

[functions.sync-representanter]
verify_jwt = false

[functions.sync-voteringer]
verify_jwt = false

[functions.generate-sak-ai]
verify_jwt = false

[functions.sync-all]
verify_jwt = false

[functions.sync-historikk]
verify_jwt = false
